### ISSUE TITLE
Add responsive design

### ISSUE THREAD

**Issue by Pranshu1902** [sonalij06/Know_Your_Lucky_Number.github.io#14]
Make the website responsive for mobile view and improve styling
![image](https://user-images.githubusercontent.com/70687348/194083530-f06141f4-ab5b-41a6-aaba-f73e24c86a87.png)

**Comment by Pranshu1902** [comment]
@sonalij06 If you find this issue valid then please assign it to me

**Comment by sonalij06** [comment]
Go Ahead!!

**Comment by Pranshu1902** [comment]
@sonalij06 On it, please add the hacktoberfest label
