### ISSUE TITLE
There is an issue in the High Score feature

### ISSUE THREAD

**Issue by InquisitiveMe15** [sonalij06/Know_Your_Lucky_Number.github.io#4]
It shows the last recent score on it, not the highest one achieved till yet.
I would like to work on this issue.
Kindly assign this to me.

Thank you :)

**Comment by koookee** [comment]
Don't forget to pull the recent changes to sync your local repo with the remote one

**Comment by sonalij06** [comment]
> Don't forget to pull the recent changes to sync your local repo with the remote one

Sure
